### ISSUE TITLE
IC item list

### ISSUE THREAD

**Issue by Phanneth7** [eprasart/kERP#3]
![ic item list](https://cloud.githubusercontent.com/assets/9510901/6733238/7569d64e-ce83-11e4-9513-8638a3fa6591.png)

**Comment by eprasart** [comment]
Fixed.
Also do the same for Category and Classification.

select i.id, i.code, i.description, description2, barcode, currency, price, d.description allow_discount, t.description as type, ca.description category, cl.description classification
from ic_item i
inner join list d on i.allow_discount = d.code
inner join list t on i.type = t.code
inner join ic_category ca on ca.code = i.category
inner join ic_classification cl on cl.code = i.classification
